#!/usr/bin/env bash
# Install the fare watcher as a recurring job.
#
#   macOS -> launchd user agent (survives reboot, no terminal needed)
#   Linux -> crontab line
#
# Usage:
#   ./install_schedule.sh --watch hk-prd-lon-scout --interval 7d
#   ./install_schedule.sh --watch hk-prd-lon-focus --interval 1d
#   ./install_schedule.sh --uninstall --watch hk-prd-lon-focus
#
# Each --watch job gets its own launcher, log and launchd label, so a weekly
# date scout and a daily focused-price check never inherit one shared cadence.
#
# Scheduled jobs do NOT inherit your shell environment, which is the single most
# common reason a working manual run fails on a timer. This installer therefore
# wraps the call in a launcher that sources credentials.env explicitly.

set -euo pipefail

SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STATE_DIR="${HOME}/.flight-fare-scanner"
BASE_LABEL="com.user.flight-fare-scanner"
CONFIG="${STATE_DIR}/config.yaml"
INTERVAL="6h"
WATCH_ID=""
UNINSTALL=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --interval)  INTERVAL="$2"; shift 2 ;;
    --config)    CONFIG="$2";   shift 2 ;;
    --watch)     WATCH_ID="$2"; shift 2 ;;
    --uninstall) UNINSTALL=1;   shift ;;
    *) echo "Unknown argument: $1" >&2; exit 2 ;;
  esac
done

JOB_NAME="all"
if [[ -n "${WATCH_ID}" ]]; then
  JOB_NAME="$(printf '%s' "${WATCH_ID}" | tr -cs 'A-Za-z0-9-' '-')"
  JOB_NAME="${JOB_NAME#-}"
  JOB_NAME="${JOB_NAME%-}"
fi
LABEL="${BASE_LABEL}.${JOB_NAME}"
PLIST="${HOME}/Library/LaunchAgents/${LABEL}.plist"
LAUNCHER="${STATE_DIR}/run-watch-${JOB_NAME}.sh"
LOG_FILE="${STATE_DIR}/watch-${JOB_NAME}.log"

# ---------------------------------------------------------------- uninstall
if [[ "${UNINSTALL}" -eq 1 ]]; then
  if [[ "$(uname)" == "Darwin" ]]; then
    launchctl bootout "gui/$(id -u)/${LABEL}" 2>/dev/null \
      || launchctl unload "${PLIST}" 2>/dev/null || true
    [[ -f "${PLIST}" ]] && mv "${PLIST}" "${PLIST}.removed" \
      && echo "launchd job removed (plist kept at ${PLIST}.removed)"
  else
    crontab -l 2>/dev/null | grep -v "flight-fare-scanner:${JOB_NAME}" | crontab - || true
    echo "crontab entry removed for ${JOB_NAME}"
  fi
  exit 0
fi

# ------------------------------------------------------------ interval parse
if ! [[ "${INTERVAL}" =~ ^[0-9]+[mhdw]$ ]]; then
  echo "--interval must look like 30m, 90m, 6h, 1d or 7d" >&2
  exit 2
fi
case "${INTERVAL}" in
  *w) SECONDS_INTERVAL=$(( ${INTERVAL%w} * 7 * 86400 )) ;;
  *d) SECONDS_INTERVAL=$(( ${INTERVAL%d} * 86400 )) ;;
  *h) SECONDS_INTERVAL=$(( ${INTERVAL%h} * 3600 )) ;;
  *m) SECONDS_INTERVAL=$(( ${INTERVAL%m} * 60 )) ;;
  *)  echo "--interval must look like 30m, 90m, 6h, 1d or 7d" >&2; exit 2 ;;
esac
if [[ "${SECONDS_INTERVAL}" -lt 900 ]]; then
  echo "Refusing an interval under 15 minutes: fares do not move that fast and" >&2
  echo "it will burn your API quota. Use 30m or longer." >&2
  exit 2
fi

# ------------------------------------------------------------- prerequisites
mkdir -p "${STATE_DIR}"

if [[ ! -f "${CONFIG}" ]]; then
  echo "Config not found at ${CONFIG}"
  echo "  cp ${SKILL_DIR}/config.example.yaml ${CONFIG}"
  exit 1
fi
if [[ ! -f "${STATE_DIR}/credentials.env" ]]; then
  echo "Credentials not found at ${STATE_DIR}/credentials.env"
  echo "  cp ${SKILL_DIR}/credentials.env.example ${STATE_DIR}/credentials.env"
  echo "  chmod 600 ${STATE_DIR}/credentials.env    # then fill in your keys"
  exit 1
fi

PYTHON="$(command -v python3)"
if [[ -z "${PYTHON}" ]]; then
  echo "python3 not found on PATH" >&2
  exit 1
fi

# Verify the selected watch before wiring up a timer that would fail silently.
set +e
# shellcheck disable=SC1091
source "${STATE_DIR}/credentials.env"
VALIDATE_ARGS=(validate --config "${CONFIG}")
if [[ -n "${WATCH_ID}" ]]; then
  VALIDATE_ARGS+=(--watch "${WATCH_ID}")
fi
"${PYTHON}" "${SKILL_DIR}/scripts/fare_watch.py" "${VALIDATE_ARGS[@]}"
VALIDATE_RC=$?
set -e
if [[ "${VALIDATE_RC}" -ne 0 ]]; then
  echo "Config validation failed - fix the errors above before scheduling." >&2
  exit 1
fi

# ---------------------------------------------------------------- launcher
cat > "${LAUNCHER}" <<LAUNCHER_EOF
#!/usr/bin/env bash
# Generated by install_schedule.sh - edit the config, not this file.
set -uo pipefail
set -a
source "${STATE_DIR}/credentials.env"
set +a
export FARE_WATCH_SCHEDULED=1
RUN_ARGS=(run --config "${CONFIG}")
if [[ -n "${WATCH_ID}" ]]; then
  RUN_ARGS+=(--watch "${WATCH_ID}")
fi
exec "${PYTHON}" "${SKILL_DIR}/scripts/fare_watch.py" "\${RUN_ARGS[@]}" \
  >> "${LOG_FILE}" 2>&1
LAUNCHER_EOF
chmod +x "${LAUNCHER}"
echo "launcher: ${LAUNCHER}"

# ---------------------------------------------------------------- schedule
if [[ "$(uname)" == "Darwin" ]]; then
  mkdir -p "${HOME}/Library/LaunchAgents"
  cat > "${PLIST}" <<PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>${LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>${LAUNCHER}</string>
  </array>
  <key>StartInterval</key><integer>${SECONDS_INTERVAL}</integer>
  <!-- Catch up after the Mac wakes from sleep instead of skipping the run. -->
  <key>RunAtLoad</key><true/>
  <key>StandardOutPath</key><string>${STATE_DIR}/launchd-${JOB_NAME}.out.log</string>
  <key>StandardErrorPath</key><string>${STATE_DIR}/launchd-${JOB_NAME}.err.log</string>
</dict>
</plist>
PLIST_EOF

  launchctl bootout "gui/$(id -u)/${LABEL}" 2>/dev/null || true
  launchctl bootstrap "gui/$(id -u)" "${PLIST}" 2>/dev/null \
    || launchctl load "${PLIST}"
  echo "launchd job installed for ${JOB_NAME}: every ${INTERVAL} (${SECONDS_INTERVAL}s)"
  echo "  status:    launchctl print gui/$(id -u)/${LABEL} | head -20"
  echo "  run now:   launchctl kickstart -k gui/$(id -u)/${LABEL}"
  echo "  logs:      tail -f ${LOG_FILE}"
  echo "  uninstall: $0 --uninstall${WATCH_ID:+ --watch ${WATCH_ID}}"
else
  if (( SECONDS_INTERVAL == 7 * 86400 )); then
    CRON_EXPR="0 9 * * 1"
  elif (( SECONDS_INTERVAL == 86400 )); then
    CRON_EXPR="0 9 * * *"
  elif (( SECONDS_INTERVAL % 86400 == 0 )); then
    CRON_EXPR="0 9 */$(( SECONDS_INTERVAL / 86400 )) * *"
  elif (( SECONDS_INTERVAL % 3600 == 0 )); then
    CRON_EXPR="0 */$(( SECONDS_INTERVAL / 3600 )) * * *"
  else
    CRON_EXPR="*/$(( SECONDS_INTERVAL / 60 )) * * * *"
  fi
  ENTRY="${CRON_EXPR} /bin/bash ${LAUNCHER} # flight-fare-scanner:${JOB_NAME}"
  ( crontab -l 2>/dev/null | grep -v "flight-fare-scanner:${JOB_NAME}"; echo "${ENTRY}" ) | crontab -
  echo "crontab entry installed for ${JOB_NAME}: ${ENTRY}"
  echo "  logs:      tail -f ${LOG_FILE}"
  echo "  uninstall: $0 --uninstall${WATCH_ID:+ --watch ${WATCH_ID}}"
fi
